name: Renovate-iOS-sample
options:
  bundleIdPrefix: com.coffmark
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.6.0
targets:
  Renovate-iOS-sample:
    type: application
    platform: iOS
    deploymentTarget: "15.5"
    sources: [Renovate-iOS-sample]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value