name: Renovate
on:
  push:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.241.11
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'